# Uncomment the next line to define a global platform for your project
platform :ios, '14.2'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

target 'AdmobAdapterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'Ads-Global'
  pod 'Pangle-adapter-for-admob'
  #pod 'Google-Mobile-Ads-SDK'


  # Pods for AdmobAdapterDemo

  target 'AdmobAdapterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdmobAdapterDemoUITests' do
    # Pods for testing
  end

end
