# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdmobAdapterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'Bytedance-UnionAD'

  # Pods for AdmobAdapterDemo

  target 'AdmobAdapterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdmobAdapterDemoUITests' do
    # Pods for testing
  end

end
